package com.salmon.dataload.helper;

public enum TableName {XINT_STOCKDATA,XINT_PRICEDATA ,XINT_STORESDATA ,XINT_MASDATA ,XINT_OFFERSDATA , XINT_LANGDATA, XINT_ATTRIBUTEDATA, XINT_PROMOTIONDATA, XINT_OFFERSATTRIBUTEDATA }